/**
 * build-stations.ts
 *
 * data/source/seoul-1-8-stations.csv 를 가공해
 *   - src/lib/data/stations.generated.ts  (전체 1~8호선 역 + 좌표 + 환승 정보)
 *   - src/lib/data/line-order.generated.ts (호선별 역 순서 배열)
 * 를 생성합니다.
 *
 * Usage:
 *   pnpm tsx scripts/build-stations.ts
 *
 * 원본 데이터 출처:
 *   https://gist.github.com/yoon-gu/902efb6d5bd345e3837e035a3c0642b8
 *   (서울 열린데이터광장 OA-12035 주소 + Naver API 좌표 보강)
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_CSV = path.join(ROOT, "data/source/seoul-1-8-stations.csv");
const OUT_DIR = path.join(ROOT, "src/lib/data");
const OUT_TS_STATIONS = path.join(OUT_DIR, "stations.generated.ts");
const OUT_TS_LINE_ORDER = path.join(OUT_DIR, "line-order.generated.ts");
const OUT_JSON = path.join(ROOT, "public/data/stations.json");

interface RawRow {
  lat: number;
  lon: number;
  name: string;
  line: string;
}

interface StationOut {
  id: string;
  name: string;
  line: string;
  lat: number;
  lng: number;
  transfers: string[];
}

function stripSuffix(name: string): string {
  // "청량리역" → "청량리"  (DB 일관성을 위해 "역" 제거)
  return name.replace(/역$/, "");
}

async function parseCSV(): Promise<RawRow[]> {
  const raw = await readFile(SRC_CSV, "utf-8");
  const lines = raw.trim().split("\n");
  // header: lat,lon,name,no_line
  return lines.slice(1).map((l) => {
    const [lat, lon, name, line] = l.split(",");
    return {
      lat: parseFloat(lat),
      lon: parseFloat(lon),
      name: stripSuffix(name.trim()),
      line: line.trim(),
    };
  });
}

function buildStations(rows: RawRow[]): { stations: StationOut[]; lineOrder: Record<string, string[]> } {
  // 같은 이름의 역이 여러 호선에 등장하면 transfers 자동 매핑
  const byName: Record<string, string[]> = {};
  for (const r of rows) {
    if (!byName[r.name]) byName[r.name] = [];
    if (!byName[r.name].includes(r.line)) byName[r.name].push(r.line);
  }

  const stations: StationOut[] = rows.map((r) => {
    const id = `${r.line}_${r.name}`;
    const transfers = byName[r.name].filter((l) => l !== r.line);
    return {
      id,
      name: r.name,
      line: r.line,
      lat: r.lat,
      lng: r.lon,
      transfers,
    };
  });

  // 호선별 역 순서 (CSV의 원본 순서 그대로 — yoon-gu 데이터는 호선별로 정렬되어 있음)
  const lineOrder: Record<string, string[]> = {};
  for (const r of rows) {
    if (!lineOrder[r.line]) lineOrder[r.line] = [];
    const id = `${r.line}_${r.name}`;
    if (!lineOrder[r.line].includes(id)) lineOrder[r.line].push(id);
  }

  return { stations, lineOrder };
}

function renderStationsTs(stations: StationOut[]): string {
  return `// AUTO-GENERATED by scripts/build-stations.ts — DO NOT EDIT MANUALLY.
// 원본: data/source/seoul-1-8-stations.csv

export interface GeneratedStation {
  id: string;
  name: string;
  line: string;
  lat: number;
  lng: number;
  transfers: string[];
}

export const GENERATED_STATIONS: GeneratedStation[] = ${JSON.stringify(stations, null, 2)};
`;
}

function renderLineOrderTs(lineOrder: Record<string, string[]>): string {
  return `// AUTO-GENERATED by scripts/build-stations.ts — DO NOT EDIT MANUALLY.

export const LINE_ORDER: Record<string, string[]> = ${JSON.stringify(lineOrder, null, 2)};

export const SUPPORTED_LINES = Object.keys(LINE_ORDER);
`;
}

async function ensureDir(dir: string) {
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

async function main() {
  if (!existsSync(SRC_CSV)) {
    console.error(`[build-stations] 원본 CSV가 없습니다: ${SRC_CSV}`);
    process.exit(1);
  }

  const rows = await parseCSV();
  const { stations, lineOrder } = buildStations(rows);

  await ensureDir(OUT_DIR);
  await ensureDir(path.dirname(OUT_JSON));

  await writeFile(OUT_TS_STATIONS, renderStationsTs(stations), "utf-8");
  await writeFile(OUT_TS_LINE_ORDER, renderLineOrderTs(lineOrder), "utf-8");
  await writeFile(
    OUT_JSON,
    JSON.stringify({ source: "yoon-gu gist + Seoul OA-12035", stations }, null, 2),
    "utf-8"
  );

  console.log(`✓ ${stations.length} 개 역 생성`);
  console.log(`✓ ${Object.keys(lineOrder).length} 개 호선 순서 데이터`);
  for (const [line, ids] of Object.entries(lineOrder)) {
    console.log(`  ${line}호선: ${ids.length}개역`);
  }
  console.log(`\n출력:`);
  console.log(`  ${path.relative(ROOT, OUT_TS_STATIONS)}`);
  console.log(`  ${path.relative(ROOT, OUT_TS_LINE_ORDER)}`);
  console.log(`  ${path.relative(ROOT, OUT_JSON)}`);
}

main().catch((err) => {
  console.error("[build-stations] 오류:", err);
  process.exit(1);
});
